using System.Linq;
using Content.Shared.Traits;
using Content.Shared._DV.Traits.Conditions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DV.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitEntry : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public event Action<bool>? OnToggled;

    public bool IsSelected => TraitCheckbox.Pressed;
    public int TraitCost { get; }

    private readonly TraitPrototype _trait;
    private bool _isUpdating;
    private string? _selectionError;
    private readonly List<string> _failedConditionTooltips = new();

    public TraitEntry(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _trait = trait;
        TraitCost = trait.Cost;

        MouseFilter = MouseFilterMode.Pass;

        TraitNameLabel.Text = Loc.GetString(trait.Name);
        TraitDescriptionLabel.SetMessage(trait.Description is { } description ? Loc.GetString(description) : string.Empty);

        var costPrefix = trait.Cost > 0 ? "+" : "";
        var costColor = trait.Cost > 0 ? "#ff6b6b" : trait.Cost < 0 ? "#6bff6b" : "#888888";
        TraitCostLabel.Text = $"{costPrefix}{trait.Cost}";
        TraitCostLabel.ModulateSelfOverride = Color.FromHex(costColor);

        TraitCheckbox.OnToggled += OnCheckboxToggled;

        UpdateConditionTooltips();
    }

    private void UpdateConditionTooltips()
    {
        var tooltips = new List<string>();

        foreach (var condition in _trait.Conditions)
        {
            var tooltip = condition.GetTooltip(_prototype, _loc);
            if (!string.IsNullOrEmpty(tooltip))
                tooltips.Add(tooltip);
        }

        if (tooltips.Count > 0)
        {
            var tooltipText = Loc.GetString("trait-conditions-tooltip",
                ("requirements", string.Join("\n", tooltips)));

            TooltipSupplier = _ => CreateMarkupTooltip(tooltipText);
        }
        else
            TooltipSupplier = null;
    }

    private static Tooltip CreateMarkupTooltip(string markupText)
    {
        var tooltip = new Tooltip();

        tooltip.SetMessage(FormattedMessage.FromMarkupOrThrow(markupText));

        return tooltip;
    }

    public void UpdateConditionsMet(string? jobId, string? speciesId, IReadOnlySet<ProtoId<TraitPrototype>>? selected = null)
    {
        _failedConditionTooltips.Clear();
        MeetsConditions = speciesId == null || !_trait.ExcludedSpecies.Any(species => species.Id == speciesId);
        if (!MeetsConditions)
            _failedConditionTooltips.Add(Loc.GetString("trait-species-excluded-tooltip"));

        foreach (var condition in _trait.Conditions)
        {
            if (CheckCondition(condition, jobId, speciesId, selected) == false)
            {
                MeetsConditions = false;
                var tooltip = condition.GetTooltip(_prototype, _loc);
                if (!string.IsNullOrEmpty(tooltip))
                    _failedConditionTooltips.Add(tooltip);
            }
        }

        UpdateDisabledState();
    }

    private bool? CheckCondition(BaseTraitCondition condition, string? job, string? species,
        IReadOnlySet<ProtoId<TraitPrototype>>? selected)
    {
        // Unknown server-only conditions stay unknown even inside inverted OR groups.
        bool? result = condition switch
        {
            IsSpeciesCondition value => species == null ? null : CheckSpeciesCondition(value, species),
            HasJobCondition value => job == null ? null : CheckJobCondition(value, job),
            InDepartmentCondition value => job == null ? null : CheckDepartmentCondition(value, job),
            AnyOfCondition value => CheckAnyOf(value, job, species, selected),
            _ => null,
        };
        if (condition is TraitDependencyCondition)
            return selected == null ? null : condition.EvaluateSelection(selected);

        return result.HasValue ? result.Value ^ condition.Invert : null;
    }

    private bool? CheckAnyOf(AnyOfCondition condition, string? job, string? species,
        IReadOnlySet<ProtoId<TraitPrototype>>? selected)
    {
        var unknown = false;
        foreach (var child in condition.Conditions)
        {
            var result = CheckCondition(child, job, species, selected);
            if (result == true)
                return true;
            unknown |= result == null;
        }

        return unknown ? null : false;
    }

    public void SetSelectionError(string? error)
    {
        _selectionError = error;
        UpdateDisabledState();
    }

    private bool CheckSpeciesCondition(IsSpeciesCondition condition, string? speciesId)
    {
        if (string.IsNullOrEmpty(speciesId))
            return false;

        return speciesId == condition.Species.Id;
    }

    private bool CheckJobCondition(HasJobCondition condition, string? jobId)
    {
        if (string.IsNullOrEmpty(jobId))
            return false;

        return jobId == condition.Job;
    }

    private bool CheckDepartmentCondition(InDepartmentCondition condition, string? jobId)
    {
        if (string.IsNullOrEmpty(jobId))
            return false;

        if (!_prototype.TryIndex(condition.Department, out var department))
            return false;

        return department.Roles.Contains(jobId);
    }

    private void UpdateDisabledState()
    {
        var unavailable = !MeetsConditions || _selectionError != null;
        TraitCheckbox.Disabled = unavailable && !IsSelected;
        TraitCheckbox.Visible = !unavailable || IsSelected;
        LockIcon.Visible = unavailable && !IsSelected;
        UpdateConditionTooltips();

        if (unavailable)
        {
            AddStyleClass("TraitsEntryDisabled");

            if (_failedConditionTooltips.Count > 0)
            {
                var tooltipText = Loc.GetString("trait-conditions-not-met-tooltip",
                    ("requirements", string.Join("\n", _failedConditionTooltips)));

                TooltipSupplier = _ => CreateMarkupTooltip(tooltipText);
            }
            else if (_selectionError is { } error)
            {
                TooltipSupplier = _ => CreateMarkupTooltip(error);
            }
        }
        else
        {
            RemoveStyleClass("TraitsEntryDisabled");
        }
    }

    private void OnCheckboxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_isUpdating)
            return;

        if ((!MeetsConditions || _selectionError != null) && args.Pressed)
        {
            _isUpdating = true;
            TraitCheckbox.Pressed = false;
            _isUpdating = false;
            return;
        }

        UpdateSelectedStyle();
        OnToggled?.Invoke(args.Pressed);
    }

    public void SetSelected(bool selected)
    {
        _isUpdating = true;
        TraitCheckbox.Pressed = selected;
        UpdateDisabledState();
        UpdateSelectedStyle();
        _isUpdating = false;
    }

    public bool MeetsConditions { get; private set; } = true;

    private void UpdateSelectedStyle()
    {
        if (TraitCheckbox.Pressed)
            AddStyleClass("TraitsEntrySelected");
        else
            RemoveStyleClass("TraitsEntrySelected");
    }
}
