using System.Linq;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitCategory : BoxContainer
{
    public event Action<ProtoId<TraitPrototype>, bool>? OnTraitToggled;

    private readonly TraitCategoryPrototype? _category;
    private readonly List<TraitPrototype> _allTraits;
    private readonly Dictionary<ProtoId<TraitPrototype>, TraitEntry> _traitEntries = new();

    private bool _isExpanded;

    public int SelectedCount;
    public int PointsSpent;

    public TraitCategory(TraitCategoryPrototype? category, List<TraitPrototype> traits)
    {
        RobustXamlLoader.Load(this);

        _category = category;
        _allTraits = traits;
        _isExpanded = category?.DefaultExpanded ?? true;

        CategoryNameLabel.Text = category == null ? Loc.GetString("trait-editor-title") : Loc.GetString(category.Name);
        SetAccentColor(category?.AccentColor ?? Color.FromHex("#4a9eff"));

        HeaderButton.OnPressed += _ => ToggleExpanded();

        PopulateTraits();
        UpdateExpandedState();
        UpdateStats();
    }

    private void SetAccentColor(Color color)
    {
        AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        CategoryNameLabel.FontColorOverride = color;
        ExpandIcon.FontColorOverride = color;
    }

    private void PopulateTraits()
    {
        TraitsContainer.RemoveAllChildren();
        _traitEntries.Clear();

        foreach (var trait in _allTraits)
        {
            var entry = new TraitEntry(trait);
            entry.OnToggled += selected => OnTraitEntryToggled(trait.ID, selected);
            _traitEntries[trait.ID] = entry;
            TraitsContainer.AddChild(entry);
        }
    }

    private void OnTraitEntryToggled(ProtoId<TraitPrototype> traitId, bool selected)
    {
        OnTraitToggled?.Invoke(traitId, selected);
    }

    private void ToggleExpanded()
    {
        _isExpanded = !_isExpanded;
        UpdateExpandedState();
    }

    private void UpdateExpandedState()
    {
        ContentPanel.Visible = _isExpanded;
        ExpandIcon.Text = _isExpanded ? "▼" : "▶";
    }

    public void UpdateStats()
    {
        SelectedCount = _traitEntries.Values.Count(e => e.IsSelected);
        PointsSpent = _traitEntries.Values
            .Where(e => e.IsSelected)
            .Sum(e => e.TraitCost);

        if (_category?.MaxTraits is >= 0)
        {
            CategoryStatsLabel.Text = Loc.GetString("trait-category-trait-count",
                ("selected", SelectedCount),
                ("max", _category.MaxTraits.Value));
        }
        else
        {
            CategoryStatsLabel.Text = Loc.GetString("trait-category-trait-count-unlimited",
                ("selected", SelectedCount));
        }

        if (_category?.PointLimit is >= 0)
        {
            CategoryPointsLabel.Visible = true;
            CategoryPointsLabel.Text = Loc.GetString("trait-category-points",
                ("selected", PointsSpent),
                ("max", _category.PointLimit.Value));
        }
        else
        {
            CategoryPointsLabel.Visible = false;
        }
    }

    public void SetTraitSelected(ProtoId<TraitPrototype> traitId, bool selected)
    {
        if (_traitEntries.TryGetValue(traitId, out var entry))
        {
            entry.SetSelected(selected);
        }
    }

    public void ClearSelection()
    {
        foreach (var (_, entry) in _traitEntries)
        {
            entry.SetSelected(false);
        }

        SelectedCount = 0;
        PointsSpent = 0;
        UpdateStats();
    }

    public IEnumerable<ProtoId<TraitPrototype>> GetSelectedTraitIds()
    {
        return _traitEntries
            .Where(kvp => kvp.Value.IsSelected)
            .Select(kvp => kvp.Key);
    }

    public void FilterTraits(string searchText)
    {
        var hasVisibleTraits = false;

        foreach (var (traitId, entry) in _traitEntries)
        {
            var trait = _allTraits.First(t => t.ID == traitId);
            var name = Loc.GetString(trait.Name);
            var description = trait.Description is { } descriptionId ? Loc.GetString(descriptionId) : string.Empty;

            var matchesSearch = string.IsNullOrEmpty(searchText) ||
                                name.Contains(searchText, StringComparison.OrdinalIgnoreCase) ||
                                description.Contains(searchText, StringComparison.OrdinalIgnoreCase);

            entry.Visible = matchesSearch;

            if (entry.Visible)
                hasVisibleTraits = true;
        }

        Visible = hasVisibleTraits;
        ContentPanel.Visible = _isExpanded || !string.IsNullOrEmpty(searchText);
    }

    public void UpdateConditions(string? jobId, string? speciesId, IReadOnlySet<ProtoId<TraitPrototype>>? selected = null)
    {
        foreach (var (_, entry) in _traitEntries)
        {
            entry.UpdateConditionsMet(jobId, speciesId, selected);
        }

        UpdateStats();
    }

    public void UpdateAvailability(Func<TraitPrototype, string?> getError)
    {
        foreach (var trait in _allTraits)
        {
            var entry = _traitEntries[trait.ID];
            entry.SetSelectionError(entry.IsSelected ? null : getError(trait));
        }
    }
}
