using System.Linq;
using Content.Shared._DV.CCVars;
using Content.Shared._QB.Traits;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitsTab : BoxContainer
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<HashSet<ProtoId<TraitPrototype>>>? OnTraitsChanged;

    private readonly Dictionary<string, TraitCategory> _categories = new();
    private HashSet<ProtoId<TraitPrototype>> _selected = new();
    private string? _job;
    private string? _species;
    private int _maxCount;
    private int _maxPoints;

    public TraitsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += _ => ApplySearch();
        _maxCount = _cfg.GetCVar(DCCVars.MaxTraitCount);
        _maxPoints = _cfg.GetCVar(DCCVars.MaxTraitPoints);
        GlobalPointsBar.Parent!.OnResized += UpdateStats;
        RefreshTraits();
    }

    private void SetMaxCount(int value)
    {
        _maxCount = value;
        UpdateSelection();
    }

    private void SetMaxPoints(int value)
    {
        _maxPoints = value;
        UpdateSelection();
    }

    private void OnProtoReload(PrototypesReloadedEventArgs args)
    {
        if (args.WasModified<TraitPrototype>() || args.WasModified<TraitCategoryPrototype>())
            RefreshTraits();
    }

    public void RefreshTraits()
    {
        CategoriesContainer.RemoveAllChildren();
        _categories.Clear();

        var groups = _prototype.EnumeratePrototypes<TraitPrototype>()
            .GroupBy(t => t.Category?.Id ?? TraitCategoryPrototype.Default)
            .OrderBy(g => _prototype.TryIndex<TraitCategoryPrototype>(g.Key, out var category) ? category.Priority : 0)
            .ThenBy(g => g.Key);

        foreach (var group in groups)
        {
            _prototype.TryIndex<TraitCategoryPrototype>(group.Key, out var category);
            var traits = group.OrderByDescending(t => t.Cost).ThenBy(t => Loc.GetString(t.Name)).ToList();
            var control = new TraitCategory(category, traits);
            control.OnTraitToggled += OnTraitToggled;
            _categories.Add(group.Key, control);
            CategoriesContainer.AddChild(control);
        }

        UpdateSelection();
        ApplySearch();
    }

    public void SetProfile(HumanoidCharacterProfile? profile, string? job)
    {
        _selected = profile == null ? new() : new(profile.TraitPreferences);
        _species = profile?.Species.Id;
        _job = job;
        UpdateSelection();
    }

    private void OnTraitToggled(ProtoId<TraitPrototype> id, bool selected)
    {
        var proposed = new HashSet<ProtoId<TraitPrototype>>(_selected);
        if (selected)
        {
            proposed.Add(id);
            var valid = TraitSelection.Validate(proposed, _prototype, _maxCount, _maxPoints);
            if (!proposed.SetEquals(valid))
            {
                UpdateSelection();
                return;
            }
        }
        else
        {
            proposed.Remove(id);
            // Removing a drawback may leave too few points for another trait.
            proposed = new(TraitSelection.Validate(proposed, _prototype, _maxCount, _maxPoints));
        }

        _selected = proposed;
        UpdateSelection();
        OnTraitsChanged?.Invoke(new(_selected));
    }

    private void UpdateSelection()
    {
        foreach (var category in _categories.Values)
        {
            category.UpdateConditions(_job, _species, _selected);
            category.ClearSelection();
            foreach (var trait in _selected)
                category.SetTraitSelected(trait, true);
            category.UpdateStats();
            category.UpdateAvailability(GetSelectionError);
        }

        UpdateStats();
    }

    private string? GetSelectionError(TraitPrototype trait)
    {
        var selected = _selected.Where(id => _prototype.HasIndex(id)).Select(id => _prototype.Index(id)).ToList();
        if (_maxCount >= 0 && selected.Count >= _maxCount)
            return Loc.GetString("disabled-traits-reason-global-limit");
        if (_maxPoints >= 0 && selected.Sum(value => value.Cost) + trait.Cost > _maxPoints)
            return Loc.GetString("trait-insufficient-points-tooltip");
        if (selected.Any(value => TraitSelection.Conflicts(trait, value)))
            return Loc.GetString("trait-selection-conflict-tooltip");

        if (_prototype.TryIndex(trait.Category, out var category))
        {
            var categoryTraits = selected.Where(value => value.Category == trait.Category).ToList();
            if (category.MaxTraits is >= 0 && categoryTraits.Count >= category.MaxTraits)
                return Loc.GetString("trait-category-full-tooltip");
            if (category.PointLimit is >= 0 && categoryTraits.Sum(value => value.Cost) + trait.Cost > category.PointLimit)
                return Loc.GetString("trait-insufficient-points-tooltip");
        }

        var proposed = new HashSet<ProtoId<TraitPrototype>>(_selected) { trait.ID };
        return proposed.SetEquals(TraitSelection.Validate(proposed, _prototype, _maxCount, _maxPoints))
            ? null : Loc.GetString("trait-selection-invalid-tooltip");
    }

    private void ApplySearch()
    {
        foreach (var category in _categories.Values)
            category.FilterTraits(SearchBar.Text.Trim());
    }

    private void UpdateStats()
    {
        var points = 0;
        foreach (var id in _selected)
        {
            if (_prototype.TryIndex(id, out var trait))
                points += trait.Cost;
        }

        GlobalTraitCountLabel.Text = _maxCount < 0
            ? Loc.GetString("trait-category-trait-count-unlimited", ("selected", _selected.Count))
            : Loc.GetString("trait-category-trait-count", ("selected", _selected.Count), ("max", _maxCount));
        GlobalPointsLabel.Text = _maxPoints < 0
            ? Loc.GetString("trait-editor-category-budgets")
            : $"{_maxPoints - points} / {_maxPoints}";

        var parent = GlobalPointsBar.Parent!;
        parent.Visible = _maxPoints >= 0;
        var fraction = _maxPoints > 0 ? Math.Clamp((float) (_maxPoints - points) / _maxPoints, 0, 1) : 0;
        GlobalPointsBar.SetWidth = Math.Max(0, parent.Width - 2) * fraction;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _prototype.PrototypesReloaded += OnProtoReload;
        _cfg.OnValueChanged(DCCVars.MaxTraitCount, SetMaxCount, true);
        _cfg.OnValueChanged(DCCVars.MaxTraitPoints, SetMaxPoints, true);
        RefreshTraits();
    }

    protected override void ExitedTree()
    {
        _prototype.PrototypesReloaded -= OnProtoReload;
        _cfg.UnsubValueChanged(DCCVars.MaxTraitCount, SetMaxCount);
        _cfg.UnsubValueChanged(DCCVars.MaxTraitPoints, SetMaxPoints);
        base.ExitedTree();
    }
}
